spring:
  application:
    name: springboot_cqrs_query
  config:
    import: optional:file:env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
          audiences:
          - https://choudai-matketplace.jp.auth0.com/api/v2/
          - https://choudai-matketplace.jp.auth0.com/userinfo
  profiles:
    active: [dev, prod]

okta:
  oauth2:
    issuer: https://${AUTH0_DOMAIN}/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

logging:
  structured:
    format:
      file: ecs

server:
  port: 8081
  servlet:
    context-path: /query
